ALTER TABLE PRODUCT_FAMILY
ADD FOREIGN KEY (TENANT_ID) REFERENCES TENANT(ID);

ALTER TABLE PRODUCT_FAMILY_CAPABILITY
ADD FOREIGN KEY (PRODUCT_FAMILY_ID) REFERENCES PRODUCT_FAMILY(ID);

--ALTER TABLE PRODUCT_FAMILY_CAPABILITY
--ADD FOREIGN KEY (CAPABILITY_NAME) REFERENCES PRODUCT_CAPABILITY(CAPABILITY_NAME);

ALTER TABLE PRODUCT_FAMILY_CAPABILITY_ENV
ADD FOREIGN KEY (PRODUCT_FAMILY_ID) REFERENCES PRODUCT_FAMILY(ID);

ALTER TABLE PRODUCT_FAMILY_CAPABILITY_CONFIG
ADD FOREIGN KEY (PRODUCT_FAMILY_ID) REFERENCES PRODUCT_FAMILY(ID);

--ALTER TABLE PRODUCT_FAMILY_CAPABILITY_CONFIG
--ADD FOREIGN KEY (CAPABILITY_NAME) REFERENCES PRODUCT_CAPABILITY(CAPABILITY_NAME);